[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
homework11 = "BYrXxhPXAxoGc4fkYEd7WkecZUnSU4ucj4LKMzGMfqw6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ZATAARA/.config/solana/devnet_test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
